parameters:
#    twentysteps_collmex.example.class: twentysteps\Bundle\CollmexBundle\Example

services:
#    twentysteps_collmex.example:
#        class: %twentysteps_collmex.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
